{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "135010a3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Everything went fine\n",
      "0.5\n",
      "Division failed\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "# try/except -> Exemplo comum\n",
    "\n",
    "def reciprocal(n):\n",
    "    try:\n",
    "        n = 1 / n\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Division failed\")\n",
    "        return None\n",
    "    else:\n",
    "        print(\"Everything went fine\")\n",
    "        return n\n",
    "\n",
    "\n",
    "print(reciprocal(2))\n",
    "print(reciprocal(0))\n",
    "   \n",
    "# Um código rotulado dessa maneira é executado quando (e somente quando) \n",
    "# nenhuma exceção foi levantada dentro da parte do bloco try:. \n",
    "# Podemos dizer que exatamente um ramo pode ser executado após o try:\n",
    "# – ou o que começa com except (não se esqueça de que pode haver mais de um ramo desse tipo)\n",
    "# ou o que começa com else.\n",
    "\n",
    "# Nota: o ramo else: deve estar localizado após o último ramo except."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "25a20f19",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Everything went fine\n",
      "It's time to say goodbye\n",
      "0.5\n",
      "\n",
      "Division failed\n",
      "It's time to say goodbye\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "# O bloco try-except pode ser estendido de mais uma forma \n",
    "# – adicionando uma parte iniciada pela palavra-chave finally\n",
    "# (deve ser o último ramo do código projetado para tratar exceções).\n",
    "\n",
    "# Nota: essas duas variantes (else e finally) não são dependentes de nenhuma forma,\n",
    "# e podem coexistir ou ocorrer de forma independente.\n",
    "\n",
    "# O bloco finally é sempre executado (ele finaliza a execução do bloco try-except, daí o seu nome),\n",
    "# não importa o que tenha acontecido anteriormente, mesmo ao levantar uma exceção,\n",
    "# independentemente de ter sido tratada ou não.\n",
    "\n",
    "def reciprocal(n):\n",
    "    try:\n",
    "        n = 1 / n\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Division failed\")\n",
    "        n = None\n",
    "    else:\n",
    "        print(\"Everything went fine\")\n",
    "    finally:\n",
    "        print(\"It's time to say goodbye\")\n",
    "        return n\n",
    "\n",
    "\n",
    "print(reciprocal(2))\n",
    "print()\n",
    "print(reciprocal(0))\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7dd93058",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "invalid literal for int() with base 10: 'Hello!'\n",
      "invalid literal for int() with base 10: 'Hello!'\n"
     ]
    }
   ],
   "source": [
    "# Exceções são classes\n",
    "# Além disso, quando uma exceção é levantada, um objeto da classe é instanciado\n",
    "# e percorre todos os níveis de execução do programa, procurando o ramo except\n",
    "# que está preparado para lidar com ela.\n",
    "\n",
    "# Esse objeto carrega algumas informações úteis que podem ajudá-lo a identificar\n",
    "# com precisão todos os aspectos da situação pendente. Para atingir esse objetivo,\n",
    "# o Python oferece uma variante especial da cláusula de exceção – você pode encontrá-la no editor.\n",
    "\n",
    "try:\n",
    "    i = int(\"Hello!\")\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    print(e.__str__())\n",
    "    \n",
    "    \n",
    "# A instrução except é estendida e contém uma frase adicional que começa com a palavra-chave as,\n",
    "# seguida por um identificador. O identificador é projetado para capturar o objeto da exceção,\n",
    "# permitindo que você analise sua natureza e tire algumas conclusões úteis.\n",
    "\n",
    "# Nota: o escopo do identificador cobre apenas o seu ramo except e não se estende além disso.\n",
    "\n",
    "# O exemplo apresenta uma maneira muito simples de utilizar o objeto recebido – apenas imprima-o\n",
    "# (como você pode ver, a saída é produzida pelo método __str__() do objeto)\n",
    "# e ele contém uma breve mensagem descrevendo o motivo.\n",
    "\n",
    "# A mesma mensagem será impressa se não houver um bloco except adequado no código,\n",
    "# e o Python for forçado a lidar com a exceção sozinho.\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c7cf6478",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "   +---BaseExceptionGroup\n",
      "   |   +---ExceptionGroup\n",
      "   +---Exception\n",
      "   |   +---ArithmeticError\n",
      "   |   |   +---FloatingPointError\n",
      "   |   |   +---OverflowError\n",
      "   |   |   +---ZeroDivisionError\n",
      "   |   |   |   +---DivisionByZero\n",
      "   |   |   |   +---DivisionUndefined\n",
      "   |   |   +---DecimalException\n",
      "   |   |   |   +---Clamped\n",
      "   |   |   |   +---Rounded\n",
      "   |   |   |   |   +---Underflow\n",
      "   |   |   |   |   +---Overflow\n",
      "   |   |   |   +---Inexact\n",
      "   |   |   |   |   +---Underflow\n",
      "   |   |   |   |   +---Overflow\n",
      "   |   |   |   +---Subnormal\n",
      "   |   |   |   |   +---Underflow\n",
      "   |   |   |   +---DivisionByZero\n",
      "   |   |   |   +---FloatOperation\n",
      "   |   |   |   +---InvalidOperation\n",
      "   |   |   |   |   +---ConversionSyntax\n",
      "   |   |   |   |   +---DivisionImpossible\n",
      "   |   |   |   |   +---DivisionUndefined\n",
      "   |   |   |   |   +---InvalidContext\n",
      "   |   +---AssertionError\n",
      "   |   +---AttributeError\n",
      "   |   |   +---FrozenInstanceError\n",
      "   |   +---BufferError\n",
      "   |   +---EOFError\n",
      "   |   |   +---IncompleteReadError\n",
      "   |   +---ImportError\n",
      "   |   |   +---ModuleNotFoundError\n",
      "   |   |   +---ZipImportError\n",
      "   |   +---LookupError\n",
      "   |   |   +---IndexError\n",
      "   |   |   +---KeyError\n",
      "   |   |   |   +---NoSuchKernel\n",
      "   |   |   |   +---UnknownBackend\n",
      "   |   |   +---CodecRegistryError\n",
      "   |   +---MemoryError\n",
      "   |   +---NameError\n",
      "   |   |   +---UnboundLocalError\n",
      "   |   +---OSError\n",
      "   |   |   +---BlockingIOError\n",
      "   |   |   +---ChildProcessError\n",
      "   |   |   +---ConnectionError\n",
      "   |   |   |   +---BrokenPipeError\n",
      "   |   |   |   +---ConnectionAbortedError\n",
      "   |   |   |   +---ConnectionRefusedError\n",
      "   |   |   |   +---ConnectionResetError\n",
      "   |   |   |   |   +---RemoteDisconnected\n",
      "   |   |   +---FileExistsError\n",
      "   |   |   +---FileNotFoundError\n",
      "   |   |   +---InterruptedError\n",
      "   |   |   |   +---InterruptedSystemCall\n",
      "   |   |   +---IsADirectoryError\n",
      "   |   |   +---NotADirectoryError\n",
      "   |   |   +---PermissionError\n",
      "   |   |   +---ProcessLookupError\n",
      "   |   |   +---TimeoutError\n",
      "   |   |   +---UnsupportedOperation\n",
      "   |   |   +---herror\n",
      "   |   |   +---gaierror\n",
      "   |   |   +---SSLError\n",
      "   |   |   |   +---SSLCertVerificationError\n",
      "   |   |   |   +---SSLZeroReturnError\n",
      "   |   |   |   +---SSLWantWriteError\n",
      "   |   |   |   +---SSLWantReadError\n",
      "   |   |   |   +---SSLSyscallError\n",
      "   |   |   |   +---SSLEOFError\n",
      "   |   |   +---Error\n",
      "   |   |   |   +---SameFileError\n",
      "   |   |   +---SpecialFileError\n",
      "   |   |   +---ExecError\n",
      "   |   |   +---ReadError\n",
      "   |   |   +---URLError\n",
      "   |   |   |   +---HTTPError\n",
      "   |   |   |   +---ContentTooShortError\n",
      "   |   |   +---BadGzipFile\n",
      "   |   +---ReferenceError\n",
      "   |   +---RuntimeError\n",
      "   |   |   +---NotImplementedError\n",
      "   |   |   |   +---ZMQVersionError\n",
      "   |   |   |   +---StdinNotImplementedError\n",
      "   |   |   +---RecursionError\n",
      "   |   |   +---_DeadlockError\n",
      "   |   |   +---BrokenBarrierError\n",
      "   |   |   +---BrokenExecutor\n",
      "   |   |   |   +---BrokenThreadPool\n",
      "   |   |   +---SendfileNotAvailableError\n",
      "   |   |   +---BrokenBarrierError\n",
      "   |   |   +---ExtractionError\n",
      "   |   |   +---VariableError\n",
      "   |   +---StopAsyncIteration\n",
      "   |   +---StopIteration\n",
      "   |   +---SyntaxError\n",
      "   |   |   +---IndentationError\n",
      "   |   |   |   +---TabError\n",
      "   |   +---SystemError\n",
      "   |   |   +---CodecRegistryError\n",
      "   |   +---TypeError\n",
      "   |   |   +---FloatOperation\n",
      "   |   |   +---MultipartConversionError\n",
      "   |   +---ValueError\n",
      "   |   |   +---UnicodeError\n",
      "   |   |   |   +---UnicodeDecodeError\n",
      "   |   |   |   +---UnicodeEncodeError\n",
      "   |   |   |   +---UnicodeTranslateError\n",
      "   |   |   +---UnsupportedOperation\n",
      "   |   |   +---JSONDecodeError\n",
      "   |   |   +---SSLCertVerificationError\n",
      "   |   |   +---Error\n",
      "   |   |   +---UnsupportedDigestmodError\n",
      "   |   |   +---AddressValueError\n",
      "   |   |   +---NetmaskValueError\n",
      "   |   |   +---IllegalMonthError\n",
      "   |   |   +---IllegalWeekdayError\n",
      "   |   |   +---ParserError\n",
      "   |   |   +---ClassNotFound\n",
      "   |   |   +---ClipboardEmpty\n",
      "   |   |   +---MessageDefect\n",
      "   |   |   |   +---NoBoundaryInMultipartDefect\n",
      "   |   |   |   +---StartBoundaryNotFoundDefect\n",
      "   |   |   |   +---CloseBoundaryNotFoundDefect\n",
      "   |   |   |   +---FirstHeaderLineIsContinuationDefect\n",
      "   |   |   |   +---MisplacedEnvelopeHeaderDefect\n",
      "   |   |   |   +---MissingHeaderBodySeparatorDefect\n",
      "   |   |   |   +---MultipartInvariantViolationDefect\n",
      "   |   |   |   +---InvalidMultipartContentTransferEncodingDefect\n",
      "   |   |   |   +---UndecodableBytesDefect\n",
      "   |   |   |   +---InvalidBase64PaddingDefect\n",
      "   |   |   |   +---InvalidBase64CharactersDefect\n",
      "   |   |   |   +---InvalidBase64LengthDefect\n",
      "   |   |   |   +---HeaderDefect\n",
      "   |   |   |   |   +---InvalidHeaderDefect\n",
      "   |   |   |   |   +---HeaderMissingRequiredValue\n",
      "   |   |   |   |   +---NonPrintableDefect\n",
      "   |   |   |   |   +---ObsoleteHeaderDefect\n",
      "   |   |   |   |   +---NonASCIILocalPartDefect\n",
      "   |   |   |   |   +---InvalidDateDefect\n",
      "   |   |   +---MacroToEdit\n",
      "   |   |   +---InvalidFileException\n",
      "   |   |   +---UnequalIterablesError\n",
      "   |   |   +---InvalidVersion\n",
      "   |   |   +---ELFInvalid\n",
      "   |   |   +---InvalidWheelFilename\n",
      "   |   |   +---InvalidSdistFilename\n",
      "   |   |   +---InvalidSpecifier\n",
      "   |   |   +---InvalidMarker\n",
      "   |   |   +---UndefinedComparison\n",
      "   |   |   +---UndefinedEnvironmentName\n",
      "   |   |   +---InvalidRequirement\n",
      "   |   |   |   +---RequirementParseError\n",
      "   |   |   +---InvalidVersion\n",
      "   |   +---Warning\n",
      "   |   |   +---BytesWarning\n",
      "   |   |   +---DeprecationWarning\n",
      "   |   |   |   +---ProvisionalWarning\n",
      "   |   |   +---EncodingWarning\n",
      "   |   |   +---FutureWarning\n",
      "   |   |   |   +---ProvisionalCompleterWarning\n",
      "   |   |   +---ImportWarning\n",
      "   |   |   +---PendingDeprecationWarning\n",
      "   |   |   +---ResourceWarning\n",
      "   |   |   +---RuntimeWarning\n",
      "   |   |   |   +---ProactorSelectorThreadWarning\n",
      "   |   |   |   +---UnknownTimezoneWarning\n",
      "   |   |   |   +---PEP440Warning\n",
      "   |   |   +---SyntaxWarning\n",
      "   |   |   +---UnicodeWarning\n",
      "   |   |   +---UserWarning\n",
      "   |   |   |   +---GetPassWarning\n",
      "   |   |   |   +---FormatterWarning\n",
      "   |   |   +---DeprecatedTzFormatWarning\n",
      "   |   |   +---PkgResourcesDeprecationWarning\n",
      "   |   +---ExceptionGroup\n",
      "   |   +---_OptionError\n",
      "   |   +---_Error\n",
      "   |   +---error\n",
      "   |   +---Error\n",
      "   |   +---SubprocessError\n",
      "   |   |   +---CalledProcessError\n",
      "   |   |   +---TimeoutExpired\n",
      "   |   +---TokenError\n",
      "   |   +---StopTokenizing\n",
      "   |   +---ClassFoundException\n",
      "   |   +---EndOfBlock\n",
      "   |   +---TraitError\n",
      "   |   +---Error\n",
      "   |   +---Error\n",
      "   |   |   +---CancelledError\n",
      "   |   |   +---InvalidStateError\n",
      "   |   +---_GiveupOnSendfile\n",
      "   |   +---error\n",
      "   |   +---Incomplete\n",
      "   |   +---InvalidStateError\n",
      "   |   +---LimitOverrunError\n",
      "   |   +---QueueEmpty\n",
      "   |   +---QueueFull\n",
      "   |   +---error\n",
      "   |   +---LZMAError\n",
      "   |   +---RegistryError\n",
      "   |   +---_GiveupOnFastCopy\n",
      "   |   +---Empty\n",
      "   |   +---Full\n",
      "   |   +---ZMQBaseError\n",
      "   |   |   +---ZMQError\n",
      "   |   |   |   +---ContextTerminated\n",
      "   |   |   |   +---Again\n",
      "   |   |   |   +---InterruptedSystemCall\n",
      "   |   |   +---ZMQBindError\n",
      "   |   |   +---NotDone\n",
      "   |   +---PickleError\n",
      "   |   |   +---PicklingError\n",
      "   |   |   +---UnpicklingError\n",
      "   |   +---_Stop\n",
      "   |   +---ArgumentError\n",
      "   |   +---COMError\n",
      "   |   +---ReturnValueIgnoredError\n",
      "   |   +---ArgumentError\n",
      "   |   +---ArgumentTypeError\n",
      "   |   +---ConfigError\n",
      "   |   |   +---ConfigLoaderError\n",
      "   |   |   |   +---ArgumentError\n",
      "   |   |   +---ConfigFileNotFound\n",
      "   |   +---ConfigurableError\n",
      "   |   |   +---MultipleInstanceError\n",
      "   |   +---ApplicationError\n",
      "   |   +---KeyReuseError\n",
      "   |   +---UnknownKeyError\n",
      "   |   +---LeakedCallbackError\n",
      "   |   +---BadYieldError\n",
      "   |   +---ReturnValueIgnoredError\n",
      "   |   +---Return\n",
      "   |   +---InvalidPortNumber\n",
      "   |   +---NoIPAddresses\n",
      "   |   +---BadZipFile\n",
      "   |   +---LargeZipFile\n",
      "   |   +---Error\n",
      "   |   |   +---NoSectionError\n",
      "   |   |   +---DuplicateSectionError\n",
      "   |   |   +---DuplicateOptionError\n",
      "   |   |   +---NoOptionError\n",
      "   |   |   +---InterpolationError\n",
      "   |   |   |   +---InterpolationMissingOptionError\n",
      "   |   |   |   +---InterpolationSyntaxError\n",
      "   |   |   |   +---InterpolationDepthError\n",
      "   |   |   +---ParsingError\n",
      "   |   |   |   +---MissingSectionHeaderError\n",
      "   |   +---BadEntryPoint\n",
      "   |   +---NoSuchEntryPoint\n",
      "   |   +---DuplicateKernelError\n",
      "   |   +---ErrorDuringImport\n",
      "   |   +---NotOneValueFound\n",
      "   |   +---CannotEval\n",
      "   |   +---OptionError\n",
      "   |   +---BdbQuit\n",
      "   |   +---Restart\n",
      "   |   +---FindCmdError\n",
      "   |   +---HomeDirError\n",
      "   |   +---ProfileDirError\n",
      "   |   +---IPythonCoreError\n",
      "   |   |   +---TryNext\n",
      "   |   |   +---UsageError\n",
      "   |   |   +---StdinNotImplementedError\n",
      "   |   +---InputRejected\n",
      "   |   +---GetoptError\n",
      "   |   +---ErrorToken\n",
      "   |   +---PrefilterError\n",
      "   |   +---AliasError\n",
      "   |   |   +---InvalidAliasError\n",
      "   |   +---Error\n",
      "   |   |   +---InterfaceError\n",
      "   |   |   +---DatabaseError\n",
      "   |   |   |   +---InternalError\n",
      "   |   |   |   +---OperationalError\n",
      "   |   |   |   +---ProgrammingError\n",
      "   |   |   |   +---IntegrityError\n",
      "   |   |   |   +---DataError\n",
      "   |   |   |   +---NotSupportedError\n",
      "   |   +---Warning\n",
      "   |   +---SpaceInInput\n",
      "   |   +---DOMException\n",
      "   |   |   +---IndexSizeErr\n",
      "   |   |   +---DomstringSizeErr\n",
      "   |   |   +---HierarchyRequestErr\n",
      "   |   |   +---WrongDocumentErr\n",
      "   |   |   +---InvalidCharacterErr\n",
      "   |   |   +---NoDataAllowedErr\n",
      "   |   |   +---NoModificationAllowedErr\n",
      "   |   |   +---NotFoundErr\n",
      "   |   |   +---NotSupportedErr\n",
      "   |   |   +---InuseAttributeErr\n",
      "   |   |   +---InvalidStateErr\n",
      "   |   |   +---SyntaxErr\n",
      "   |   |   +---InvalidModificationErr\n",
      "   |   |   +---NamespaceErr\n",
      "   |   |   +---InvalidAccessErr\n",
      "   |   |   +---ValidationErr\n",
      "   |   +---ValidationError\n",
      "   |   +---EditReadOnlyBuffer\n",
      "   |   +---_Retry\n",
      "   |   +---InvalidLayoutError\n",
      "   |   +---HeightIsUnknownError\n",
      "   |   +---GuardRejection\n",
      "   |   +---ParserSyntaxError\n",
      "   |   +---InternalParseError\n",
      "   |   +---_PositionUpdatingFinished\n",
      "   |   +---SimpleGetItemNotFound\n",
      "   |   +---UncaughtAttributeError\n",
      "   |   +---HasNoContext\n",
      "   |   +---ParamIssue\n",
      "   |   +---_JediError\n",
      "   |   |   +---InternalError\n",
      "   |   |   +---WrongVersion\n",
      "   |   |   +---RefactoringError\n",
      "   |   +---OnErrorLeaf\n",
      "   |   +---InvalidPythonEnvironment\n",
      "   |   +---MessageError\n",
      "   |   |   +---MessageParseError\n",
      "   |   |   |   +---HeaderParseError\n",
      "   |   |   |   +---BoundaryError\n",
      "   |   |   +---MultipartConversionError\n",
      "   |   |   +---CharsetError\n",
      "   |   +---HTTPException\n",
      "   |   |   +---NotConnected\n",
      "   |   |   +---InvalidURL\n",
      "   |   |   +---UnknownProtocol\n",
      "   |   |   +---UnknownTransferEncoding\n",
      "   |   |   +---UnimplementedFileMode\n",
      "   |   |   +---IncompleteRead\n",
      "   |   |   +---ImproperConnectionState\n",
      "   |   |   |   +---CannotSendRequest\n",
      "   |   |   |   +---CannotSendHeader\n",
      "   |   |   |   +---ResponseNotReady\n",
      "   |   |   +---BadStatusLine\n",
      "   |   |   |   +---RemoteDisconnected\n",
      "   |   |   +---LineTooLong\n",
      "   |   +---InteractivelyDefined\n",
      "   |   +---KillEmbedded\n",
      "   |   +---Error\n",
      "   |   |   +---NoSuchProcess\n",
      "   |   |   |   +---ZombieProcess\n",
      "   |   |   +---AccessDenied\n",
      "   |   |   +---TimeoutExpired\n",
      "   |   +---Error\n",
      "   |   +---TimeoutExpired\n",
      "   |   +---TimeoutAbandoned\n",
      "   |   +---QueueEmpty\n",
      "   |   +---QueueFull\n",
      "   |   +---DebuggerInitializationError\n",
      "   |   +---ExpatError\n",
      "   |   +---Error\n",
      "   |   |   +---ProtocolError\n",
      "   |   |   +---ResponseError\n",
      "   |   |   +---Fault\n",
      "   |   +---ParserSyntaxError\n",
      "   |   +---ResolutionError\n",
      "   |   |   +---VersionConflict\n",
      "   |   |   |   +---ContextualVersionConflict\n",
      "   |   |   +---DistributionNotFound\n",
      "   |   |   +---UnknownExtra\n",
      "   |   +---_Error\n",
      "   |   +---UnableToResolveVariableException\n",
      "   |   +---InvalidTypeInArgsException\n",
      "   +---GeneratorExit\n",
      "   +---KeyboardInterrupt\n",
      "   +---SystemExit\n",
      "   +---CancelledError\n",
      "   +---AbortThread\n"
     ]
    }
   ],
   "source": [
    "# Todas as exceções integradas do Python formam uma hierarquia de classes. \n",
    "\n",
    "# Este programa exibe todas as classes de exceção predefinidas em Python\n",
    "# na forma de uma impressão em formato de árvore.\n",
    "\n",
    "# Como uma árvore é um exemplo perfeito de uma estrutura de dados recursiva,\n",
    "# a recursão parece ser a melhor ferramenta para percorrê-la.\n",
    "# A função print_exception_tree() recebe dois argumentos:\n",
    "\n",
    "# um ponto dentro da árvore de onde começamos a percorrer;\n",
    "# um nível de aninhamento (que usaremos para construir um desenho simplificado dos ramos da árvore).\n",
    "# Vamos começar pela raiz da árvore – a raiz das classes de exceção do Python é a classe BaseException\n",
    "# (que é a superclasse de todas as outras exceções).\n",
    "\n",
    "# Para cada uma das classes encontradas, realizamos o mesmo conjunto de operações:\n",
    "\n",
    "# imprimir seu nome, obtido da propriedade __name__;\n",
    "# iterar pela lista de subclasses fornecidas pelo método __subclasses__(),\n",
    "# e invocar recursivamente a função print_exception_tree(),\n",
    "# incrementando o nível de aninhamento respectivamente.\n",
    "# Observe como desenhamos os ramos e bifurcações.\n",
    "\n",
    "# A impressão não está ordenada de nenhuma forma. \n",
    "# Há algumas sutis imprecisões na maneira como alguns ramos são apresentados.\n",
    "\n",
    "def print_exception_tree(thisclass, nest = 0):\n",
    "    if nest > 1:\n",
    "        print(\"   |\" * (nest - 1), end=\"\")\n",
    "    if nest > 0:\n",
    "        print(\"   +---\", end=\"\")\n",
    "\n",
    "    print(thisclass.__name__)\n",
    "\n",
    "    for subclass in thisclass.__subclasses__():\n",
    "        print_exception_tree(subclass, nest + 1)\n",
    "\n",
    "\n",
    "print_exception_tree(BaseException)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f4293213",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " :  : \n",
      "my exception : my exception : my exception\n",
      "('my', 'exception') : ('my', 'exception') : ('my', 'exception')\n"
     ]
    }
   ],
   "source": [
    "# A classe BaseException introduz uma propriedade chamada args.\n",
    "# É uma tupla projetada para reunir todos os argumentos passados ao construtor da classe.\n",
    "# Ela está vazia se o construtor foi invocado sem nenhum argumento,\n",
    "# ou contém apenas um elemento quando o construtor recebe um argumento\n",
    "# (não contamos o argumento self aqui), e assim por diante.\n",
    "\n",
    "\n",
    "def print_args(args):\n",
    "    lng = len(args)\n",
    "    if lng == 0:\n",
    "        print(\"\")\n",
    "    elif lng == 1:\n",
    "        print(args[0])\n",
    "    else:\n",
    "        print(str(args))\n",
    "\n",
    "\n",
    "try:\n",
    "    raise Exception\n",
    "except Exception as e:\n",
    "    print(e, e.__str__(), sep=' : ' ,end=' : ')\n",
    "    print_args(e.args)\n",
    "\n",
    "try:\n",
    "    raise Exception(\"my exception\")\n",
    "except Exception as e:\n",
    "    print(e, e.__str__(), sep=' : ', end=' : ')\n",
    "    print_args(e.args)\n",
    "\n",
    "try:\n",
    "    raise Exception(\"my\", \"exception\")\n",
    "except Exception as e:\n",
    "    print(e, e.__str__(), sep=' : ', end=' : ')\n",
    "    print_args(e.args)\n",
    "  \n",
    "\n",
    "# Utilizamos a função para imprimir o conteúdo da propriedade args em três casos diferentes,\n",
    "# onde a exceção da classe Exception é levantada de três maneiras distintas.\n",
    "# Para tornar isso mais ilustrativo, também imprimimos o próprio objeto,\n",
    "# junto com o resultado da invocação de __str__().\n",
    "\n",
    "# O primeiro caso parece rotineiro – há apenas o nome Exception após a palavra-chave raise.\n",
    "# Isso significa que o objeto dessa classe foi criado de maneira bastante padrão.\n",
    "\n",
    "# Os segundo e terceiro casos podem parecer um pouco estranhos à primeira vista,\n",
    "# mas não há nada de incomum aqui – são apenas invocações do construtor.\n",
    "# Na segunda instrução raise, o construtor é invocado com um argumento, e na terceira, com dois.\n",
    "\n",
    "# Como você pode ver, a saída do programa reflete isso, mostrando o conteúdo apropriado da propriedade args:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8a50e904",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Division by zero\n",
      "Division by zero\n",
      "\n",
      "Original division by zero\n",
      "My division by zero\n"
     ]
    }
   ],
   "source": [
    "# Como criar sua própria exceção\n",
    "\n",
    "# A hierarquia de exceções não é fechada nem finalizada, e você pode sempre estendê-la se quiser\n",
    "# ou precisar criar seu próprio conjunto de exceções.\n",
    "\n",
    "# Isso pode ser útil quando você cria um módulo complexo que detecta erros e levanta exceções,\n",
    "# e deseja que essas exceções sejam facilmente distinguíveis de outras trazidas pelo Python.\n",
    "\n",
    "# Isso é feito definindo suas próprias novas exceções como subclasses derivadas das exceções predefinidas.\n",
    "\n",
    "# Nota: Se você quiser criar uma exceção que será utilizada como um caso especializado de qualquer exceção embutida,\n",
    "# derive-a apenas dessa. Se quiser construir sua própria hierarquia e não deseja que ela esteja intimamente conectada à árvore de exceções do Python, derive-a de uma das classes de exceção de nível superior, como Exception.\n",
    "\n",
    "# Imagine que você criou uma nova aritmética, regida por suas próprias leis e teoremas.\n",
    "# É claro que a divisão também foi redefinida e deve se comportar de maneira diferente da divisão rotineira.\n",
    "# Também é evidente que essa nova divisão deve levantar sua própria exceção,\n",
    "# diferente da exceção embutida ZeroDivisionError, mas é razoável supor que,\n",
    "# em algumas circunstâncias, você (ou o usuário da sua aritmética) \n",
    "# possa querer tratar todas as divisões por zero da mesma maneira.\n",
    "\n",
    "\n",
    "class MyZeroDivisionError(ZeroDivisionError):\t\n",
    "    pass\n",
    "\n",
    "def do_the_division(mine):\n",
    "    if mine:\n",
    "        raise MyZeroDivisionError(\"some worse news\")\n",
    "    else:\t\t\n",
    "        raise ZeroDivisionError(\"some bad news\")\n",
    "\n",
    "\n",
    "for mode in [False, True]:\n",
    "    try:\n",
    "        do_the_division(mode)\n",
    "    except ZeroDivisionError:\n",
    "        print('Division by zero')\n",
    "\n",
    "print()        \n",
    "        \n",
    "for mode in [False, True]:\n",
    "    try:\n",
    "        do_the_division(mode)\n",
    "    except MyZeroDivisionError:\n",
    "        print('My division by zero')\n",
    "    except ZeroDivisionError:\n",
    "        print('Original division by zero')\n",
    "\n",
    "        \n",
    "\n",
    "# Vamos analisar o código:\n",
    "\n",
    "# Definimos nossa própria exceção, chamada MyZeroDivisionError, derivada da exceção embutida ZeroDivisionError.\n",
    "# Como você pode ver, decidimos não adicionar novos componentes à classe.\n",
    "\n",
    "# Como resultado, uma exceção dessa classe pode ser tratada de duas formas,\n",
    "# dependendo do ponto de vista desejado: como uma simples ZeroDivisionError ou de maneira separada.\n",
    "\n",
    "# A função do_the_division() levanta uma exceção MyZeroDivisionError ou ZeroDivisionError,\n",
    "# dependendo do valor do argumento.\n",
    "\n",
    "# A função é invocada quatro vezes no total.\n",
    "# As duas primeiras invocações são tratadas usando apenas um ramo except (o mais geral),\n",
    "# e as duas últimas com dois ramos diferentes, capazes de distinguir as exceções \n",
    "# (não se esqueça: a ordem dos ramos faz uma diferença fundamental!).\n",
    "\n",
    "# Quando você pretende construir um universo completamente novo, \n",
    "# cheio de novas entidades que não têm nada em comum com as coisas familiares,\n",
    "# pode ser interessante criar sua própria estrutura de exceções.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0045e428",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pizza ready!\n",
      "too much cheese : 110\n",
      "no such pizza on the menu : mafia\n"
     ]
    }
   ],
   "source": [
    "# Por exemplo, se você estiver trabalhando em um grande sistema de simulação destinado a modelar\n",
    "# as atividades de uma pizzaria, pode ser desejável formar uma hierarquia separada de exceções.\n",
    "\n",
    "# Você pode começar a construí-la definindo uma exceção geral como uma nova classe base\n",
    "# para qualquer outra exceção especializada. \n",
    "\n",
    "# Dessa maneira:\n",
    "\n",
    "class PizzaError(Exception):\n",
    "    def __init__(self, pizza, message):\n",
    "        Exception.__init__(self, message)\n",
    "        self.pizza = pizza\n",
    "        \n",
    "\n",
    "# Nota: Vamos coletar informações mais específicas do que uma exceção regular faria,\n",
    "# então nosso construtor aceitará dois argumentos:\n",
    "\n",
    "# Um que especifica uma pizza como o sujeito do processo.\n",
    "# Outro que contém uma descrição mais ou menos precisa do problema.\n",
    "# Como você pode ver, passamos o segundo parâmetro para o construtor da superclasse e salvamos\n",
    "# o primeiro em nossa própria propriedade.\n",
    "\n",
    "# Um problema mais específico (como um excesso de queijo) pode exigir uma exceção mais específica.\n",
    "# É possível derivar a nova classe da já definida PizzaError, como fizemos aqui:\n",
    "\n",
    "class TooMuchCheeseError(PizzaError):\n",
    "    def __init__(self, pizza, cheese, message):\n",
    "        PizzaError._init__(self, pizza, message)\n",
    "        self.cheese = cheese\n",
    "\n",
    "\n",
    "# A exceção TooMuchCheeseError precisa de mais informações do que a exceção regular PizzaError,\n",
    "# então a adicionamos ao construtor – o nome cheese é armazenado para processamento futuro.\n",
    "\n",
    "# Veja o código no editor. Nós agrupamos as duas exceções previamente\n",
    "# definidas e as utilizamos em um pequeno exemplo.\n",
    "\n",
    "class PizzaError(Exception):\n",
    "    def __init__(self, pizza, message):\n",
    "        Exception.__init__(self, message)\n",
    "        self.pizza = pizza\n",
    "\n",
    "\n",
    "class TooMuchCheeseError(PizzaError):\n",
    "    def __init__(self, pizza, cheese, message):\n",
    "        PizzaError.__init__(self, pizza, message)\n",
    "        self.cheese = cheese\n",
    "\n",
    "\n",
    "def make_pizza(pizza, cheese):\n",
    "    if pizza not in ['margherita', 'capricciosa', 'calzone']:\n",
    "        raise PizzaError(pizza, \"no such pizza on the menu\")\n",
    "    if cheese > 100:\n",
    "        raise TooMuchCheeseError(pizza, cheese, \"too much cheese\")\n",
    "    print(\"Pizza ready!\")\n",
    "\n",
    "for (pz, ch) in [('calzone', 0), ('margherita', 110), ('mafia', 20)]:\n",
    "    try:\n",
    "        make_pizza(pz, ch)\n",
    "    except TooMuchCheeseError as tmce:\n",
    "        print(tmce, ':', tmce.cheese)\n",
    "    except PizzaError as pe:\n",
    "        print(pe, ':', pe.pizza)\n",
    "\n",
    "\n",
    "# Uma dessas exceções é levantada dentro da função make_pizza()\n",
    "# quando qualquer uma das duas situações errôneas é descoberta:\n",
    "# um pedido de pizza incorreto ou um pedido de queijo em excesso.\n",
    "\n",
    "# Nota:\n",
    "# Remover o ramo que começa com except TooMuchCheeseError fará com que todas as exceções\n",
    "# aparecidas sejam classificadas como PizzaError.\n",
    "# Remover o ramo que começa com except PizzaError fará com que as exceções\n",
    "# TooMuchCheeseError permaneçam não tratadas, resultando na terminação do programa.\n",
    "# A solução anterior, embora elegante e eficiente, tem uma fraqueza importante.\n",
    "\n",
    "# Devido à maneira um pouco flexível de declarar os construtores,\n",
    "# as novas exceções não podem ser usadas como estão sem uma lista completa de argumentos necessários."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "0dcbd8e3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pizza ready!\n",
      " : >100\n",
      " : unknown\n"
     ]
    }
   ],
   "source": [
    "#  Vamos remover essa fraqueza definindo valores padrão para todos os parâmetros do construtor.\n",
    "\n",
    "class PizzaError(Exception):\n",
    "    def __init__(self, pizza='unknown', message=''):\n",
    "        Exception.__init__(self, message)\n",
    "        self.pizza = pizza\n",
    " \n",
    " \n",
    "class TooMuchCheeseError(PizzaError):\n",
    "    def __init__(self, pizza='uknown', cheese='>100', message=''):\n",
    "        PizzaError.__init__(self, pizza, message)\n",
    "        self.cheese = cheese\n",
    " \n",
    " \n",
    "def make_pizza(pizza, cheese):\n",
    "    if pizza not in ['margherita', 'capricciosa', 'calzone']:\n",
    "        raise PizzaError\n",
    "    if cheese > 100:\n",
    "        raise TooMuchCheeseError\n",
    "    print(\"Pizza ready!\")\n",
    " \n",
    " \n",
    "for (pz, ch) in [('calzone', 0), ('margherita', 110), ('mafia', 20)]:\n",
    "    try:\n",
    "        make_pizza(pz, ch)\n",
    "    except TooMuchCheeseError as tmce:\n",
    "        print(tmce, ':', tmce.cheese)\n",
    "    except PizzaError as pe:\n",
    "        print(pe, ':', pe.pizza)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df6da422",
   "metadata": {},
   "source": [
    "## RESUMO\n",
    "\n",
    "\n",
    "- O ramo else: da instrução try é executado quando não houve nenhuma exceção durante a execução do bloco try:.\n",
    "\n",
    "- O ramo finally: da instrução try é sempre executado.\n",
    "\n",
    "- A sintaxe except Exception_Name as exception_object: permite interceptar um objeto que carrega informações sobre uma exceção pendente. A propriedade do objeto chamada args (uma tupla) armazena todos os argumentos passados ao construtor do objeto.\n",
    "\n",
    "- As classes de exceção podem ser estendidas para enriquecê-las com novas funcionalidades ou para adaptar seus traços a exceções recém-definidas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "d5401106",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "success done\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    assert __name__ == \"__main__\"\n",
    "except:\n",
    "    print(\"fail\", end=' ')\n",
    "else:\n",
    "    print(\"success\", end=' ')\n",
    "finally:\n",
    "    print(\"done\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "4326422d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.0\n",
      "fine\n"
     ]
    }
   ],
   "source": [
    "# Pergunta 1: Qual é a saída esperada do seguinte código?\n",
    "\n",
    "import math\n",
    " \n",
    "try:\n",
    "    print(math.sqrt(9))\n",
    "except ValueError:\n",
    "    print(\"inf\")\n",
    "else:\n",
    "    print(\"fine\")\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "09e973c1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "inf\n",
      "the end\n"
     ]
    }
   ],
   "source": [
    "# Pergunta 2: Qual é a saída esperada do seguinte código?\n",
    "\n",
    "import math # cmath... funcionaria\n",
    " \n",
    "try:\n",
    "    print(math.sqrt(-9)) # math não calcula raiz de numeos negativos, tinha q ser cmath\n",
    "except ValueError:\n",
    "    print(\"inf\")\n",
    "else:\n",
    "    print(\"fine\")\n",
    "finally:\n",
    "    print(\"the end\")\n",
    "\n",
    "    \n",
    "# Se tivesse usado cmath, o resulatdo seria 3j que representa a raiz quadrada de -9 \n",
    "# no domínio dos números complexos, onde j é a unidade imaginária.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "174cd5ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enemy warning! Red alert! High readiness! "
     ]
    }
   ],
   "source": [
    "# Pergunta 3: Qual é a saída esperada do seguinte código?\n",
    "\n",
    "import math\n",
    " \n",
    "class NewValueError(ValueError):\n",
    "    def __init__(self, name, color, state):\n",
    "        self.data = (name, color, state)\n",
    " \n",
    "try:\n",
    "    raise NewValueError(\"Enemy warning\", \"Red alert\", \"High readiness\")\n",
    "except NewValueError as nve:\n",
    "    for arg in nve.args:\n",
    "        print(arg, end='! ')\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "197d0dc3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
